name: "Become QMK Bot"
description: "Configures git user as QMK Bot"
runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "QMK Bot"
        git config --global user.email "hello@qmk.fm"
