name: CLI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GO:
      uses: docker://qmkfm/base_container
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        bin/qmk pytest
