name: Format Codebase

on:
  push:
    branches:
    - master

jobs:
  format:
    runs-on: ubuntu-latest
    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y dos2unix

    - name: Format files
      run: |
        bin/qmk cformat -a
        bin/qmk pyformat
        bin/qmk fileformat

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        author: QMK Bot <hello@qmk.fm>
        committer: QMK Bot <hello@qmk.fm>
        commit-message: Format code according to conventions
        title: '[CI] Format code according to conventions'
