name: Regenerate Files

on:
  push:
    branches:
    - master
    - develop

jobs:
  regen:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v3

    - name: Run qmk generators
      shell: 'bash {0}'
      run: |
        qmk generate-keycodes --version latest > quantum/keycodes.h
        git diff

    - uses: rlespinasse/github-slug-action@v3.x

    - uses: ./.github/actions/become-bot

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      if: ${{ github.repository == 'qmk/qmk_firmware'}}
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        delete-branch: true
        branch: bugfix/format_${{ env.GITHUB_REF_SLUG }}
        author: QMK Bot <hello@qmk.fm>
        committer: QMK Bot <hello@qmk.fm>
        commit-message: Regenerate Files
        title: '[CI] Regenerate Files'
